name: Rhino Syntax Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-syntax:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download Mozilla Rhino 1.9.1
        run: |
          curl -sL "https://repo1.maven.org/maven2/org/mozilla/rhino-all/1.9.1/rhino-all-1.9.1.jar" -o rhino.jar

      - name: Check syntax for ./base.js
        run: |
          java -cp rhino.jar org.mozilla.javascript.tools.jsc.Main ./base.js
i
